### ISSUE TITLE
createca should not allow to create a CA with an empty issuer/subject

### ISSUE THREAD

**Issue by dereulenspiegel** [johndoe31415/x509sak#7]
When setting the subject name of a CA it should not be possible to specify an invalid subject like `/DN=My root CA`. Setting an invalid subject like this causes x509sak to create a CA certificate with empty issuer and subject fields. This CA can actually be used to create certificates, but they won't validate against this CA, since the issuer field of these certificates is empty as well.
Imho specifying a subject which leads to an empty field value should generate an user visible error.

**Comment by johndoe31415** [comment]
Yikes.

Nice catch, although solving this is not going to be straightforward: This is essentially OpenSSL's fault:

```
$ openssl req -new -key CA.key  -subj '/DN=hUIhfdiu' -text
req: Skipping unknown subject name attribute "DN"
Certificate Request:
    Data:
        Version: 1 (0x0)
        Subject: 
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (384 bit)
                pub:
                    04:04:06:9a:db:17:33:06:95:45:b9:97:15:91:89:
                    30:c9:8d:b4:ca:38:55:8c:6f:c1:da:fd:60:73:58:
                    d3:33:9f:7c:d4:5c:4d:26:2c:3a:a5:d7:b7:66:67:
                    5e:b4:88:ac:1a:a0:9a:d8:a5:a5:b7:1c:f9:01:5a:
                    8f:ce:80:1b:55:51:11:17:07:f3:f0:21:cd:5d:ec:
                    b4:e7:f6:fb:71:03:1e:c6:7e:27:ce:a2:dd:86:f8:
                    e0:5b:e1:27:6e:2a:66
                ASN1 OID: secp384r1
                NIST CURVE: P-384
        Attributes:
            (none)
            Requested Extensions:
    Signature Algorithm: ecdsa-with-SHA256
    Signature Value:
        30:65:02:31:00:bc:ad:77:9e:3e:15:a5:2e:5a:4f:b4:bf:b4:
        a2:05:12:de:f4:bb:a8:9c:f6:06:34:fd:66:96:45:49:eb:67:
        93:06:26:4d:9b:b5:d2:f4:8c:13:4e:ec:d5:2e:e3:7a:2a:02:
        30:07:4c:29:c3:24:e8:03:5b:5c:dc:e6:37:8f:e8:47:3d:da:
        f5:b3:ab:df:3a:34:7a:50:0f:e1:ab:c4:31:5b:47:aa:c0:13:
        d0:08:2c:c6:73:4e:e1:af:13:e5:5f:1d:57
-----BEGIN CERTIFICATE REQUEST-----
MIH3MH8CAQAwADB2MBAGByqGSM49AgEGBSuBBAAiA2IABAQGmtsXMwaVRbmXFZGJ
MMmNtMo4VYxvwdr9YHNY0zOffNRcTSYsOqXXt2ZnXrSIrBqgmtilpbcc+QFaj86A
G1VRERcH8/AhzV3stOf2+3EDHsZ+J86i3Yb44FvhJ24qZqAAMAoGCCqGSM49BAMC
A2gAMGUCMQC8rXeePhWlLlpPtL+0ogUS3vS7qJz2BjT9ZpZFSetnkwYmTZu10vSM
E07s1S7jeioCMAdMKcMk6ANbXNzmN4/oRz3a9bOr3zo0elAP4avEMVtHqsAT0Ags
xnNO4a8T5V8dVw==
-----END CERTIFICATE REQUEST-----
```

In other words, OpenSSL silently discards the unknown subject and gives a returncode of 0.

So to actually solve this properly would mean manually parsing the DN-string (which, given the numerous corner cases, is not trivial in itself), then validating it and serializing it for OpenSSL.

Ideally, there would be some option inside OpenSSL to fail loudly and proudly instead of silently discarding this nasty error. I'll need to check if there is such an option.

**Comment by johndoe31415** [comment]
Oh, wait! OpenSSL DOES emit a warning.

So the next-best botchy thing would be to parse the output text and then raise an error. Way easier but also a lot less robust.
